#
###################################
# Site wide configuration
####################################
#
title: Matthias Naets
email: naets_matthias@hotmail.com
description: Matthias' blog
url: https://MatthN.github.io # the base hostname & protocol for your site
keywords: ["data science", "R", "python", "blog"]

#
###################################
# Jekyll configuration
####################################
#
timezone:          Europe/Brussels
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

plugins:
  - jekyll-gist
  - jemoji

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Matthias Naets
  avatar: avatar.jpg
  job: "Senior Product Analyst"
  bio: "I am deeply passionate about exploring the realms of data analysis and data science, constantly seeking innovative ways to harness data for insightful discoveries and solutions."
  email: naets_matthias@hotmail
  disqus-shortname: #username
  twitter:  #username
  facebook: #username
  google:
    plus: #username
    analytics: UA-62251910-2
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: MatthN #username
  stackoverflow: 
  linkedin: matthias-naets #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
  telegram: #username
